---
apiVersion: v1
kind: Service
metadata:
  name: matchmaker
  annotations:   ## 내용 추가 (ICCS Load Balancer에 연동)
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    role: matchmaker-server
  type: LoadBalancer
